version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: nestjs_mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretrootpassword
      MYSQL_DATABASE: curses
      MYSQL_USER: QweAsdZxc23
      MYSQL_PASSWORD: YES
      MARIADB_AUTO_UPGRADE: 0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: QweAsdZxc23
      DATABASE_PASSWORD: YES
      DATABASE_NAME: curses
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

volumes:
  db_data: