version: '3.8'

services:
  db:
    image: mariadb:latest

    container_name: nestjs_mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretrootpassword
      MYSQL_DATABASE: curses
      MYSQL_USER: QweAsdZxc23
      MYSQL_PASSWORD: YES
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
